# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Prova primer
email: your-email@domain.com
description: Towards naledi.css
baseurl: "/prova-primer" # the subpath of your site, e.g. /blog
twitter_username: jekyllrb
github_username:  jekyll

exclude:
    - node_modules

sass:
    load_paths:
        - node_modules

# Build settings
markdown: kramdown
